version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    container_name: moodle-mariadb
    ports:
      - '${MARIADB_EXPOSED_PORT}:3306'
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/bitnami/mariadb
  moodle:
    image: docker.io/bitnami/moodle:3.11.3
    container_name: moodle
    ports:
      - '${MOODLE_EXPOSED_PORT}:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=${MARIADB_EXPOSED_PORT}
      - MOODLE_DATABASE_USER=${MARIADB_USER}
      - MOODLE_DATABASE_NAME=${MARIADB_DATABASE}
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb
  moodle-setup:
    build: ./moodle-setup
    container_name: moodle-setup
    environment:
      - MARIADB_PORT=3306
      - MOODLE_PORT=8080
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
    volumes:
      - moodle_data:/usr/src/app/moodle_data
      - ./config.json:/usr/src/app/config.json:ro
volumes:
  moodle_data:
  moodledata_data:
  mariadb_data:
